-- Ported from SQL Server RetailReportingDemo.dbo.vw_* - see 01_functions.sql header.

CREATE OR REPLACE VIEW VW_ORDERLINEDETAIL AS
SELECT
    ol.ORDERLINEID,
    o.ORDERID,
    o.ORDERDATE,
    o.STATUS,
    c.CUSTOMERID,
    c.CUSTOMERNAME,
    c.SEGMENT,
    c.REGIONID,
    e.EMPLOYEEID,
    e.FULLNAME       AS EMPLOYEENAME,
    e.COMMISSIONTIER,
    p.PRODUCTID,
    p.PRODUCTNAME,
    p.CATEGORYID,
    p.UNITCOST,
    ol.QUANTITY,
    ol.UNITPRICE,
    ol.DISCOUNTPCT,
    FN_NETLINEAMOUNT(ol.QUANTITY, ol.UNITPRICE, ol.DISCOUNTPCT) AS NETAMOUNT
FROM ORDERLINES ol
JOIN ORDERS o    ON o.ORDERID = ol.ORDERID
JOIN PRODUCTS p  ON p.PRODUCTID = ol.PRODUCTID
JOIN CUSTOMERS c ON c.CUSTOMERID = o.CUSTOMERID
JOIN EMPLOYEES e ON e.EMPLOYEEID = o.EMPLOYEEID;
/

CREATE OR REPLACE VIEW VW_CUSTOMERORDERSUMMARY AS
SELECT
    CUSTOMERID,
    CUSTOMERNAME,
    SEGMENT,
    COUNT(DISTINCT ORDERID) AS TOTALORDERS,
    SUM(NETAMOUNT)          AS TOTALNETAMOUNT,
    MIN(ORDERDATE)          AS FIRSTORDERDATE,
    MAX(ORDERDATE)          AS LASTORDERDATE
FROM VW_ORDERLINEDETAIL
GROUP BY CUSTOMERID, CUSTOMERNAME, SEGMENT;
/

CREATE OR REPLACE VIEW VW_ACTIVEINVENTORYSTATUS AS
SELECT
    i.PRODUCTID,
    p.PRODUCTNAME,
    i.WAREHOUSEID,
    w.WAREHOUSENAME,
    w.REGIONID,
    r.REGIONNAME,
    i.QUANTITYONHAND,
    i.REORDERPOINT,
    i.LASTRESTOCKDATE,
    CASE WHEN i.QUANTITYONHAND < i.REORDERPOINT THEN 1 ELSE 0 END AS ISBELOWREORDERPOINT
FROM INVENTORY i
JOIN PRODUCTS p   ON p.PRODUCTID = i.PRODUCTID
JOIN WAREHOUSES w ON w.WAREHOUSEID = i.WAREHOUSEID
JOIN REGIONS r    ON r.REGIONID = w.REGIONID;
/

CREATE OR REPLACE VIEW VW_EMPLOYEEREGIONMAP AS
SELECT
    e.EMPLOYEEID,
    e.FULLNAME,
    e.COMMISSIONTIER,
    e.HIREDATE,
    e.REGIONID,
    r.REGIONNAME,
    r.COUNTRY
FROM EMPLOYEES e
JOIN REGIONS r ON r.REGIONID = e.REGIONID;
/

CREATE OR REPLACE VIEW VW_RETURNSDETAIL AS
SELECT
    rt.RETURNID,
    rt.RETURNDATE,
    rt.QUANTITY AS RETURNEDQUANTITY,
    rt.REASON,
    ol.ORDERLINEID,
    ol.ORDERID,
    p.PRODUCTID,
    p.PRODUCTNAME,
    p.CATEGORYID
FROM RETURNS rt
JOIN ORDERLINES ol ON ol.ORDERLINEID = rt.ORDERLINEID
JOIN PRODUCTS p    ON p.PRODUCTID = ol.PRODUCTID;
/
