-- Ported from SQL Server RetailReportingDemo.dbo.usp_* - see 01_functions.sql
-- header. SQL Server's multi-stage #temp-table pipelines are collapsed into
-- single WITH-clause (CTE) INSERT...SELECT statements per report - same logic,
-- more idiomatic Oracle, and it plays to OIA's column-level lineage parser's
-- strength (it resolves INSERT...SELECT column-by-column via sqlglot).
-- TRUNCATE is DDL and can't run directly inside a PL/SQL block, hence EXECUTE
-- IMMEDIATE with a literal string - OIA's harvester treats a bare literal
-- EXECUTE IMMEDIATE as statically resolvable, not a dynamic-SQL gap.

CREATE OR REPLACE PROCEDURE USP_LOOKUPCUSTOMERSEGMENT
IS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE STAGINGCUSTOMERSEGMENT';

    INSERT INTO STAGINGCUSTOMERSEGMENT (CUSTOMERID, CUSTOMERNAME, SEGMENT, REGIONID)
    SELECT CUSTOMERID, CUSTOMERNAME, SEGMENT, REGIONID
    FROM CUSTOMERS;
END USP_LOOKUPCUSTOMERSEGMENT;
/

CREATE OR REPLACE PROCEDURE USP_STAGECOMPLETEDORDERLINES(
    p_start_date IN DATE,
    p_end_date   IN DATE
)
IS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE STAGINGCOMPLETEDORDERLINES';

    INSERT INTO STAGINGCOMPLETEDORDERLINES (
        ORDERLINEID, ORDERID, ORDERDATE, FISCALPERIOD, CUSTOMERID, CUSTOMERNAME,
        REGIONID, EMPLOYEEID, EMPLOYEENAME, COMMISSIONTIER, PRODUCTID, PRODUCTNAME,
        CATEGORYID, UNITCOST, QUANTITY, UNITPRICE, DISCOUNTPCT, NETAMOUNT
    )
    SELECT
        ORDERLINEID, ORDERID, ORDERDATE, FN_FISCALPERIOD(ORDERDATE), CUSTOMERID, CUSTOMERNAME,
        REGIONID, EMPLOYEEID, EMPLOYEENAME, COMMISSIONTIER, PRODUCTID, PRODUCTNAME,
        CATEGORYID, UNITCOST, QUANTITY, UNITPRICE, DISCOUNTPCT, NETAMOUNT
    FROM VW_ORDERLINEDETAIL
    WHERE STATUS = 'Completed'
      AND ORDERDATE BETWEEN p_start_date AND p_end_date;
END USP_STAGECOMPLETEDORDERLINES;
/

CREATE OR REPLACE PROCEDURE USP_BUILDREPORT_CUSTOMERCHURNRISK
IS
BEGIN
    USP_LOOKUPCUSTOMERSEGMENT();

    EXECUTE IMMEDIATE 'TRUNCATE TABLE REPORT_CUSTOMERCHURNRISK';

    INSERT INTO REPORT_CUSTOMERCHURNRISK (
        CUSTOMERID, CUSTOMERNAME, SEGMENT, REGIONID, LASTORDERDATE, DAYSSINCELASTORDER,
        TOTALORDERS, TOTALNETAMOUNT, CHURNRISKSCORE, RISKBAND, GENERATEDAT
    )
    WITH active_customer_orders AS (
        -- deliberately independent of the shared completed-order-lines staging table
        SELECT
            c.CUSTOMERID,
            o.ORDERID,
            o.ORDERDATE,
            FN_NETLINEAMOUNT(ol.QUANTITY, ol.UNITPRICE, ol.DISCOUNTPCT) AS NETAMOUNT
        FROM CUSTOMERS c
        JOIN ORDERS o ON o.CUSTOMERID = c.CUSTOMERID AND o.STATUS = 'Completed'
        JOIN ORDERLINES ol ON ol.ORDERID = o.ORDERID
        WHERE c.ISACTIVE = 1
    ),
    rfm AS (
        SELECT
            CUSTOMERID,
            MAX(ORDERDATE)          AS LASTORDERDATE,
            COUNT(DISTINCT ORDERID) AS TOTALORDERS,
            SUM(NETAMOUNT)          AS TOTALNETAMOUNT
        FROM active_customer_orders
        GROUP BY CUSTOMERID
    ),
    enriched AS (
        SELECT
            s.CUSTOMERID,
            s.CUSTOMERNAME,
            s.SEGMENT,
            s.REGIONID,
            r.LASTORDERDATE,
            TRUNC(SYSDATE) - TRUNC(r.LASTORDERDATE) AS DAYSSINCELASTORDER,
            NVL(r.TOTALORDERS, 0)                   AS TOTALORDERS,
            NVL(r.TOTALNETAMOUNT, 0)                AS TOTALNETAMOUNT
        FROM STAGINGCUSTOMERSEGMENT s
        LEFT JOIN rfm r ON r.CUSTOMERID = s.CUSTOMERID
        WHERE EXISTS (SELECT 1 FROM CUSTOMERS c WHERE c.CUSTOMERID = s.CUSTOMERID AND c.ISACTIVE = 1)
    ),
    scored AS (
        SELECT
            CUSTOMERID, CUSTOMERNAME, SEGMENT, REGIONID, LASTORDERDATE, DAYSSINCELASTORDER, TOTALORDERS, TOTALNETAMOUNT,
            (
                (CASE
                    WHEN DAYSSINCELASTORDER IS NULL THEN 100
                    WHEN DAYSSINCELASTORDER > 365   THEN 100
                    WHEN DAYSSINCELASTORDER > 180   THEN 70
                    WHEN DAYSSINCELASTORDER > 90    THEN 40
                    ELSE 10
                 END) * 0.6
                +
                (CASE
                    WHEN TOTALORDERS = 0  THEN 100
                    WHEN TOTALORDERS <= 2 THEN 60
                    WHEN TOTALORDERS <= 5 THEN 30
                    ELSE 5
                 END) * 0.4
            ) AS CHURNRISKSCORE
        FROM enriched
    )
    SELECT
        CUSTOMERID, CUSTOMERNAME, SEGMENT, REGIONID, LASTORDERDATE, DAYSSINCELASTORDER,
        TOTALORDERS, TOTALNETAMOUNT, ROUND(CHURNRISKSCORE, 2),
        CASE
            WHEN CHURNRISKSCORE >= 70 THEN 'High'
            WHEN CHURNRISKSCORE >= 40 THEN 'Medium'
            ELSE 'Low'
        END,
        SYSTIMESTAMP
    FROM scored;
END USP_BUILDREPORT_CUSTOMERCHURNRISK;
/

CREATE OR REPLACE PROCEDURE USP_BUILDREPORT_EMPLOYEECOMMISSION(
    p_start_date IN DATE DEFAULT NULL,
    p_end_date   IN DATE DEFAULT NULL
)
IS
    v_start_date DATE := NVL(p_start_date, ADD_MONTHS(TRUNC(SYSDATE), -24));
    v_end_date   DATE := NVL(p_end_date, TRUNC(SYSDATE));
BEGIN
    USP_STAGECOMPLETEDORDERLINES(v_start_date, v_end_date);

    EXECUTE IMMEDIATE 'TRUNCATE TABLE REPORT_EMPLOYEECOMMISSION';

    INSERT INTO REPORT_EMPLOYEECOMMISSION (
        EMPLOYEEID, EMPLOYEENAME, FISCALPERIOD, COMMISSIONTIER, TOTALSALES, COMMISSIONRATE, COMMISSIONAMOUNT, GENERATEDAT
    )
    WITH employee_agg AS (
        SELECT EMPLOYEEID, FISCALPERIOD, SUM(NETAMOUNT) AS TOTALSALES
        FROM STAGINGCOMPLETEDORDERLINES
        GROUP BY EMPLOYEEID, FISCALPERIOD
    ),
    enriched AS (
        -- current commission tier looked up fresh from Employees rather than the
        -- staged snapshot (tiers can change after staging)
        SELECT
            a.EMPLOYEEID,
            e.FULLNAME AS EMPLOYEENAME,
            a.FISCALPERIOD,
            e.COMMISSIONTIER,
            a.TOTALSALES
        FROM employee_agg a
        JOIN EMPLOYEES e ON e.EMPLOYEEID = a.EMPLOYEEID
    )
    SELECT
        EMPLOYEEID, EMPLOYEENAME, FISCALPERIOD, COMMISSIONTIER, TOTALSALES,
        CASE COMMISSIONTIER
            WHEN 'Platinum' THEN 8.00
            WHEN 'Gold'     THEN 6.00
            WHEN 'Silver'   THEN 4.00
            ELSE 2.50
        END,
        TOTALSALES * CASE COMMISSIONTIER
            WHEN 'Platinum' THEN 0.08
            WHEN 'Gold'     THEN 0.06
            WHEN 'Silver'   THEN 0.04
            ELSE 0.025
        END,
        SYSTIMESTAMP
    FROM enriched;
END USP_BUILDREPORT_EMPLOYEECOMMISSION;
/

CREATE OR REPLACE PROCEDURE USP_BUILDREPORT_INVENTORYREPLENISHMENT
IS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE REPORT_INVENTORYREPLENISHMENT';

    INSERT INTO REPORT_INVENTORYREPLENISHMENT (
        PRODUCTID, PRODUCTNAME, WAREHOUSEID, WAREHOUSENAME, QUANTITYONHAND, REORDERPOINT,
        RECENTDEMAND, SUPPLIERLEADTIMEDAYS, SUGGESTEDREORDERQTY, GENERATEDAT
    )
    WITH low_stock AS (
        SELECT PRODUCTID, WAREHOUSEID, QUANTITYONHAND, REORDERPOINT
        FROM INVENTORY
        WHERE QUANTITYONHAND <= REORDERPOINT
    ),
    recent_demand AS (
        SELECT ol.PRODUCTID, SUM(ol.QUANTITY) AS RECENTDEMAND
        FROM ORDERLINES ol
        JOIN ORDERS o ON o.ORDERID = ol.ORDERID
        WHERE o.ORDERDATE >= TRUNC(SYSDATE) - 60
        GROUP BY ol.PRODUCTID
    ),
    enriched AS (
        SELECT
            ls.PRODUCTID,
            p.PRODUCTNAME,
            ls.WAREHOUSEID,
            w.WAREHOUSENAME,
            ls.QUANTITYONHAND,
            ls.REORDERPOINT,
            NVL(rd.RECENTDEMAND, 0) AS RECENTDEMAND,
            p.SUPPLIERLEADTIMEDAYS
        FROM low_stock ls
        JOIN PRODUCTS p ON p.PRODUCTID = ls.PRODUCTID
        JOIN WAREHOUSES w ON w.WAREHOUSEID = ls.WAREHOUSEID
        LEFT JOIN recent_demand rd ON rd.PRODUCTID = ls.PRODUCTID
    )
    SELECT
        PRODUCTID, PRODUCTNAME, WAREHOUSEID, WAREHOUSENAME, QUANTITYONHAND, REORDERPOINT,
        RECENTDEMAND, SUPPLIERLEADTIMEDAYS,
        CASE
            WHEN (CEIL((RECENTDEMAND / 60.0) * SUPPLIERLEADTIMEDAYS) + REORDERPOINT - QUANTITYONHAND) < 0 THEN 0
            ELSE CEIL((RECENTDEMAND / 60.0) * SUPPLIERLEADTIMEDAYS) + REORDERPOINT - QUANTITYONHAND
        END,
        SYSTIMESTAMP
    FROM enriched;
END USP_BUILDREPORT_INVENTORYREPLENISHMENT;
/

CREATE OR REPLACE PROCEDURE USP_BUILDREPORT_MONTHLYSALESBYREGION(
    p_start_date IN DATE DEFAULT NULL,
    p_end_date   IN DATE DEFAULT NULL
)
IS
    v_start_date DATE := NVL(p_start_date, ADD_MONTHS(TRUNC(SYSDATE), -24));
    v_end_date   DATE := NVL(p_end_date, TRUNC(SYSDATE));
BEGIN
    USP_STAGECOMPLETEDORDERLINES(v_start_date, v_end_date);
    USP_LOOKUPCUSTOMERSEGMENT();

    EXECUTE IMMEDIATE 'TRUNCATE TABLE REPORT_MONTHLYSALESBYREGION';

    INSERT INTO REPORT_MONTHLYSALESBYREGION (
        REGIONID, REGIONNAME, FISCALPERIOD, TOTALNETAMOUNT, PRIORPERIODAMOUNT, GROWTHPCT, TOPSEGMENT, GENERATEDAT
    )
    WITH region_period_agg AS (
        SELECT
            REGIONID,
            FISCALPERIOD,
            MIN(ORDERDATE) AS PERIODSTART,
            SUM(NETAMOUNT) AS TOTALNETAMOUNT
        FROM STAGINGCOMPLETEDORDERLINES
        GROUP BY REGIONID, FISCALPERIOD
    ),
    region_segment_agg AS (
        SELECT
            s.REGIONID,
            x.FISCALPERIOD,
            s.SEGMENT,
            SUM(x.NETAMOUNT) AS SEGMENTAMOUNT,
            ROW_NUMBER() OVER (PARTITION BY s.REGIONID, x.FISCALPERIOD ORDER BY SUM(x.NETAMOUNT) DESC) AS RN
        FROM STAGINGCOMPLETEDORDERLINES x
        JOIN STAGINGCUSTOMERSEGMENT s ON s.CUSTOMERID = x.CUSTOMERID
        GROUP BY s.REGIONID, x.FISCALPERIOD, s.SEGMENT
    ),
    enriched AS (
        SELECT
            a.REGIONID,
            r.REGIONNAME,
            a.FISCALPERIOD,
            a.TOTALNETAMOUNT,
            LAG(a.TOTALNETAMOUNT) OVER (PARTITION BY a.REGIONID ORDER BY a.PERIODSTART) AS PRIORPERIODAMOUNT,
            seg.SEGMENT AS TOPSEGMENT
        FROM region_period_agg a
        JOIN REGIONS r ON r.REGIONID = a.REGIONID
        LEFT JOIN region_segment_agg seg
          ON seg.REGIONID = a.REGIONID AND seg.FISCALPERIOD = a.FISCALPERIOD AND seg.RN = 1
    )
    SELECT
        REGIONID,
        REGIONNAME,
        FISCALPERIOD,
        TOTALNETAMOUNT,
        PRIORPERIODAMOUNT,
        CASE
            WHEN PRIORPERIODAMOUNT IS NULL OR PRIORPERIODAMOUNT = 0 THEN NULL
            ELSE ROUND((TOTALNETAMOUNT - PRIORPERIODAMOUNT) / PRIORPERIODAMOUNT * 100, 2)
        END,
        TOPSEGMENT,
        SYSTIMESTAMP
    FROM enriched;
END USP_BUILDREPORT_MONTHLYSALESBYREGION;
/

CREATE OR REPLACE PROCEDURE USP_BUILDREPORT_PRODUCTPERFORMANCE(
    p_start_date IN DATE DEFAULT NULL,
    p_end_date   IN DATE DEFAULT NULL
)
IS
    v_start_date DATE := NVL(p_start_date, ADD_MONTHS(TRUNC(SYSDATE), -24));
    v_end_date   DATE := NVL(p_end_date, TRUNC(SYSDATE));
BEGIN
    USP_STAGECOMPLETEDORDERLINES(v_start_date, v_end_date);

    EXECUTE IMMEDIATE 'TRUNCATE TABLE REPORT_PRODUCTPERFORMANCE';

    INSERT INTO REPORT_PRODUCTPERFORMANCE (
        PRODUCTID, PRODUCTNAME, CATEGORYID, CATEGORYNAME, TOTALQUANTITY, TOTALREVENUE, TOTALCOST, MARGINPCT, GENERATEDAT
    )
    WITH product_agg AS (
        SELECT
            PRODUCTID,
            SUM(QUANTITY)            AS TOTALQUANTITY,
            SUM(NETAMOUNT)           AS TOTALREVENUE,
            SUM(QUANTITY * UNITCOST) AS TOTALCOST
        FROM STAGINGCOMPLETEDORDERLINES
        GROUP BY PRODUCTID
    ),
    enriched AS (
        SELECT
            a.PRODUCTID,
            p.PRODUCTNAME,
            p.CATEGORYID,
            cat.CATEGORYNAME,
            a.TOTALQUANTITY,
            a.TOTALREVENUE,
            a.TOTALCOST
        FROM product_agg a
        JOIN PRODUCTS p ON p.PRODUCTID = a.PRODUCTID
        JOIN PRODUCTCATEGORIES cat ON cat.CATEGORYID = p.CATEGORYID
    )
    SELECT
        PRODUCTID, PRODUCTNAME, CATEGORYID, CATEGORYNAME, TOTALQUANTITY, TOTALREVENUE, TOTALCOST,
        CASE WHEN TOTALREVENUE = 0 THEN NULL ELSE ROUND((TOTALREVENUE - TOTALCOST) / TOTALREVENUE * 100, 2) END,
        SYSTIMESTAMP
    FROM enriched;
END USP_BUILDREPORT_PRODUCTPERFORMANCE;
/
